# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://rasertingl.github.io/Raserting.io/" # the base hostname & protocol for your site

# User setting
owner:
email:“lurizhongtian@163.com”
facebook_username:
twitter_username:
github_username:RasertingL
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown